spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:tcp://localhost/~/springblog}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}

#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
  h2:
    console:
      enabled: true
#      위의 코드가 하는 역할이 뭐지?
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create
#    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
#        default_batch_fetch_size: 1000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID:dummy-google-id}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET:dummy-google-secret}
            scope:
              - email
              - profile

jwt:
  issuer: ${JWT_ISSUER:local-issuer}
  secret-Key: ${JWT_SECRET_KEY:test-secret-key-default-value-should-be-at-least-32-chars-long-1234}

#  오류수정

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace000
