spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/springblog
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create
#    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
#        default_batch_fetch_size: 1000



logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace000