#워크플로 이름 지정
name: CI

#워크플로가 시작될 조건 지정(트리거 지정)
on:
  push:
    branches: [ main ]
    
jobs: 
  build:
    runs-on: ubuntu-latest #실행 환경 지정
    #실행 스탭 지정 (실행 스텝 그룹화)
    #uses(작업), run(명령어)-`name`으로 스텝의 이름 지정
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
